### PR TITLE
Standalone at-sign

### PR DESCRIPTION
**Pull request by psteckler**
#29 was not really what @gares was after. That PR allowed you to use `@` is the first character of an identifier within a notation.

This PR allows you to write `@@` as a completely separate identifier, so you can write things like:
```
{? @@} @ident
```
where the `@@` gets rendered as just `@`. This PR supersedes #29.

**Kind:** feature

### CODE REVIEW

**Comment by gares** [comment]
It now parses fine, but the rendering is not what I expect
screenshot from 2018-02-22 14-41-39
`@` should be black and bold, as the `*` in the end of the line (that breaks cause the rule is too long)

**Comment by psteckler** [comment]
How does this look:
screenshot from 2018-02-22 14-58-49
?

**Comment by psteckler** [comment]
With the last change, you can write simply
```
{+ @} @ident
```
A `@` that is not followed by characters that might be part of an identifier will be considered a separate token (an "atom"), and should render in black.

**Comment by maximedenes** [comment]
This needs a rebase.

**Comment by gares** [comment]
I need this one, but I don't know how to regenerate the .py file

**Comment by psteckler** [comment]
@gares rebased on `sphinx-doc`, regenerated `.py` file, force-pushed

**Pull request merged**
