### PR TITLE
Reference manual, Sphinx version, Chapter 4, part 1, (Draft)

### PR DESCRIPTION
**Pull request by richardlford**
**Kind:** documentation

This pull request contains the complete conversion of Chapter 4 of the
Coq Reference manual to Sphinx format.

@maximedenes, or others working on this, please provide any feedback with suggestions for improvement.

Also note:
- I increased the timeout in coqtop.py a little as I was having problems with timeout.

### CODE REVIEW

**Comment by maximedenes** [comment]
Thanks a lot for contributing! @psteckler, can you have a quick look? I'm a bit busy with the WG and preparing the Sphinx infrastructure PR. Thanks!

**Comment by psteckler** [comment]
@maximedenes I will take a look soon.

**Comment by richardlford** [comment]
I've now completed the draft version of Chapter 4. I'll be doing further proof-reading, but in the meantime would appreciate any feedback.

**Comment by richardlford** [comment]
I rebased up to latest on sphinx-doc branch.

**Comment by richardlford** [comment]
I did what I think is my final edit pass on the document. As far as I can tell it is now complete and correct with respect to the previous official 8.7.1 manual. In a few places I took some inline equations and made them display equations where I thought it would improve readability. Otherwise it looks close to the original.

This should be merged after my Chapter 5 changes. I will rebase one last time after that has happened. 

Or of course if there is some feedback I'll be glad to respond to that.

**Comment by maximedenes** [comment]
@psteckler Can you have a look?

**Comment by richardlford** [comment]
I've done the final rebase and squash, fixing a couple problems in the preamble.
I also moved the top level header of chapter 5 to the beginning where it belongs and 
fixed a TODO reference from chapter 5 to chapter 4 so it resolves properly.

@maximedenes, so I think this is all ready to merge (unless some other feedback is forthcoming).

**Comment by psteckler** [comment]
Will look now briefly.

**Comment by psteckler** [comment]
I built the chapter OK.

The entry `Typing Rules` in the table of contents displays differently (bolder) than the others. 

Incidentally, I had not put these by-chapter TOC in the chapters I converted. Probably we want them, in which case we should add that as an issue.

In the typing rules, for the construct `foo \in Bar`, there's no space around the `in`, which looks not so nice. 

For the mutual inductive declarations, in the TeX version, I see `Ind [1]` where in some of the Sphinx ones, I see `Ind []`.

There's a `TODO` after `TreeExample`. Is that meant to stay in?

In the section about impredicative `Set`, there's a sentence about the "ordinary coqtop command". In the chapter "The Coq commands", I put all the names like `coqtop`, `coqc`, etc., enclosed in single backticks. If that's a good idea (?), we should do that uniformly.

Other than these nits, looks very good!

**Comment by richardlford** [comment]
I push fixes to respond to the above comments. See my comments on the new commit for details.
I think this should be ready for merge now.

**Comment by psteckler** [comment]
Here's what I see for some rules that have `in` and `not in`:
cic
For some reason, the `\in` is showing up as a literal **in**, sometimes, and with bad spacing. Maybe there's something about my browser setup that causes this.

The generated HTML looks fine, so I think this is an issue on my machine.

**Comment by richardlford** [comment]
Seeing the literal "in" rather than the "is an element of" symbol is something I had prior to fixing a problem in the preamble. The macro \in is the latex macro for "is an element of". At one point I had mistakenly redefined it to get the keyword "in" and notices the symptom you had. Part of this PR is correcting that problem by using \In as the macro for the in keyword. Perhaps you did not incorporate that fix in your testing.

**Pull request merged**
