### PR TITLE
Sphinx Reference Manual, Chapter 5 Draft

### PR DESCRIPTION
**Pull request by richardlford**
This is the Sphinx version of Chapter 5 (Module System) of the Coq reference manual. It is complete and correct as far as I know. But I'll be doing an additional edit pass to cross-check. In the meantime any feedback would be welcome.

Note that I plan to submit a separate PR to alphabetize the preamble and replaces, and when that has been merged I'll alphabetize those files here as well and push again.

@maximedenes or @psteckler, please review.

### CODE REVIEW

**Comment by richardlford** [comment]
I've now rebased this with the latest, the preamble is alphabetized and I removed the temporary :numbered: which I had put in the index.rst. So barring other feedback, I think this is ready to merge.

**Comment by psteckler** [comment]
@richardlford Thanks for getting that done!

**Comment by richardlford** [comment]
I found one small problem in the preamble changes. In the line defining \mto 
the \newcommand had accidentally been changed to \Newcommand, which 
of course did not work. I've corrected this, squashed and repushed.

**Comment by maximedenes** [comment]
Thank you!

**Pull request merged**
