### PR TITLE
Add back omega plugin clutter ;-)

### PR DESCRIPTION
**Pull request by samuelgruetter**
Here's a way to properly deprecate omega, before deleting it completely: The plugin structure is kept in place, but the only thing the omega plugin does is to emit a deprecation warning and then to call lia.

As the title suggests, it adds back some clutter, but in return, users who never dared to request that their project be on Coq's CI will have a much better updating experience.

Tested with [bbv](https://github.com/mit-plv/bbv/), which only required [minimal changes](https://github.com/mit-plv/bbv/pull/17), and with [riscv-coq](https://github.com/mit-plv/riscv-coq), which required no changes as of https://github.com/mit-plv/riscv-coq/commit/bf1facf77df0b49029b8c27c5bd8c9e54ed649f7.

### CODE REVIEW

**Review by maximedenes — CHANGES_REQUESTED** [review]
Thanks but:
1- I don't think this is necessary. Remember we do make breaking changes in major versions. User experience in this case (if they were not provided with a patch already): they update Coq, `Require Import Coq.omega.Omega` breaks, they search for `omega` in changes, they change one line in a backward-compatible way.
2- This patch adds quite some noise in the makefile and may lead to confusion, looking as if (r)omega still existed.
3- If we wanted to do this, we should obviously use the tactic deprecation machinery instead of an ad-hoc warning.

**Comment by maximedenes** [comment]
Above is not a request for changes, but Github has nothing else.

**Comment by maximedenes** [comment]
Final note: my PR already contains a deprecation warning. The breaking change is just for people who hard coded the logical path of `Omega` in their script.

**Comment by gares** [comment]
why I'm getting pinged on this one? Are code owners "gh-clone-transitive"? OMG

**Comment by Zimmi48** [comment]
@gares You were probably made a contributor of Maxime's fork at some point. Otherwise, GitHub wouldn't request reviews from you (the CODEOWNER file is there but GitHub won't request reviews from people who do not have write-access).

**Pull request closed without merging**
