### PR TITLE
Sphinx/ssr

### PR DESCRIPTION
**Pull request by amahboubi**
**Kind:** documentation

Warning: The last commit is half-blind because of troubles with compiling the html.

### CODE REVIEW

**Comment by maximedenes** [comment]
Thanks @amahboubi ! Can you let me know on which commit/branch this is based? There seems to be some conflicts with this branch, I want to make sure I get it right.

**Comment by amahboubi** [comment]
Hi @maximedenes. I am sorry I did not manage to resolve the conflicts myself... The branch is based on commit a91d73cb63205b3aed7196d9754735b2211c48a7

**Comment by maximedenes** [comment]
Don't worry, I'll figure it out. Thanks again!

**Comment by amahboubi** [comment]
If I can help let me know. But I will probably have time to devote to this only tomorrow.

**Comment by gares** [comment]
I did the rebase and the merge

**Pull request closed without merging**
